### ISSUE TITLE
Plugin and example project don't compile (master)

### ISSUE THREAD

**Issue by pzmarzly** [llogiq/mutagen#135]
```text
⋊> ~/mutagen on master ◦ cargo +nightly build
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
⋊> ~/mutagen on master ◦ cd examples/example_project/
⋊> ~/m/e/example_project on master ◦ cargo +nightly mutagen
   Compiling mutagen-plugin v0.1.1 (/home/pzmarzly/mutagen/plugin)
error: Could not compile `mutagen-plugin`.

To learn more, run the command again with --verbose.
cargo test returned non-zero status
⋊> ~/m/e/example_project on master ◦ cargo +nightly mutagen --verbose
       Fresh version_check v0.1.5
       Fresh bitflags v1.0.4
       Fresh lazy_static v1.1.0
       Fresh mutagen v0.1.1 (/home/pzmarzly/mutagen)
   Compiling mutagen-plugin v0.1.1 (/home/pzmarzly/mutagen/plugin)
     Running `sccache rustc --crate-name mutagen_plugin /home/pzmarzly/mutagen/plugin/src/lib.rs --color always --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=af423b38cac74637 --out-dir /home/pzmarzly/mutagen/examples/example_project/target/debug/deps -C incremental=/home/pzmarzly/mutagen/examples/example_project/target/debug/incremental -L dependency=/home/pzmarzly/mutagen/examples/example_project/target/debug/deps --extern bitflags=/home/pzmarzly/mutagen/examples/example_project/target/debug/deps/libbitflags-1e36badf165d6d5c.rlib --extern mutagen=/home/pzmarzly/mutagen/examples/example_project/target/debug/deps/libmutagen-e2f7ef1a882fe632.rlib`
error: Could not compile `mutagen-plugin`.

Caused by:
  process didn't exit successfully: `sccache rustc --crate-name mutagen_plugin /home/pzmarzly/mutagen/plugin/src/lib.rs --color always --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=af423b38cac74637 --out-dir /home/pzmarzly/mutagen/examples/example_project/target/debug/deps -C incremental=/home/pzmarzly/mutagen/examples/example_project/target/debug/incremental -L dependency=/home/pzmarzly/mutagen/examples/example_project/target/debug/deps --extern bitflags=/home/pzmarzly/mutagen/examples/example_project/target/debug/deps/libbitflags-1e36badf165d6d5c.rlib --extern mutagen=/home/pzmarzly/mutagen/examples/example_project/target/debug/deps/libmutagen-e2f7ef1a882fe632.rlib` (exit code: 1)
cargo test returned non-zero status
⋊> ~/m/e/example_project on master ◦ cargo +nightly test
   Compiling mutagen-plugin v0.1.1 (/home/pzmarzly/mutagen/plugin)
error[E0432]: unresolved import `syntax::codemap`
  --> /home/pzmarzly/mutagen/plugin/src/lib.rs:18:13
   |
18 | use syntax::codemap::{Span, Spanned};
   |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
  --> /home/pzmarzly/mutagen/plugin/src/lib.rs:23:19
   |
23 | use syntax::util::small_vector::SmallVector;
   |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`

error[E0432]: unresolved import `syntax::codemap`
 --> /home/pzmarzly/mutagen/plugin/src/bounded_loop.rs:3:13
  |
3 | use syntax::codemap::Span;
  |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
 --> /home/pzmarzly/mutagen/plugin/src/bounded_loop.rs:9:19
  |
9 | use syntax::util::small_vector::SmallVector;
  |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`

error[E0432]: unresolved import `syntax::codemap`
 --> /home/pzmarzly/mutagen/examples/example_project/target/debug/build/mutagen-plugin-e1ba816502005ee9/out/plugin_ops.rs:3:13
  |
3 | use syntax::codemap::Span;
  |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0603]: struct `ThinVec` is private
 --> /home/pzmarzly/mutagen/examples/example_project/target/debug/build/mutagen-plugin-e1ba816502005ee9/out/plugin_ops.rs:2:72
  |
2 | use syntax::ast::{Attribute, BinOp, BinOpKind, Expr, ExprKind, NodeId, ThinVec};
  |                                                                        ^^^^^^^

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ptr::P<syntax::ast::Item>; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/lib.rs:93:46
   |
93 |             Annotatable::Item(p.fold_item(i).expect_one("expected exactly one item"))
   |                                              ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use syntax::fold::ExpectOne;
   |

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::TraitItem; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/lib.rs:96:34
   |
96 |             p.fold_trait_item(i).expect_one("expected exactly one item")
   |                                  ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use syntax::fold::ExpectOne;
   |

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::ImplItem; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/lib.rs:99:33
   |
99 |             p.fold_impl_item(i).expect_one("expected exactly one item")
   |                                 ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use syntax::fold::ExpectOne;
   |

error[E0599]: no method named `codemap` found for type `&'a mut syntax::ext::base::ExtCtxt<'cx>` in the current scope
   --> /home/pzmarzly/mutagen/plugin/src/lib.rs:147:33
    |
147 |         let span_desc = self.cx.codemap().span_to_string(span);
    |                                 ^^^^^^^

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::Stmt; 1]>` in the current scope
   --> /home/pzmarzly/mutagen/plugin/src/lib.rs:988:84
    |
988 |                 let _ = mem::replace(&mut newstmts[0], resizer.fold_stmt(coverage).expect_one("?"));
    |                                                                                    ^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
    |
9   | use syntax::fold::ExpectOne;
    |

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ptr::P<syntax::ast::Item>; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/bounded_loop.rs:26:51
   |
26 |             Annotatable::Item(plugin.fold_item(i).expect_one("expected exactly one item"))
   |                                                   ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::TraitItem; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/bounded_loop.rs:29:39
   |
29 |             plugin.fold_trait_item(i).expect_one("expected exactly one item")
   |                                       ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::ImplItem; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/bounded_loop.rs:32:38
   |
32 |             plugin.fold_impl_item(i).expect_one("expected exactly one item")
   |                                      ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::Stmt; 1]>` in the current scope
  --> /home/pzmarzly/mutagen/plugin/src/bounded_loop.rs:80:84
   |
80 |                 let _ = mem::replace(&mut newstmts[0], resizer.fold_stmt(counters).expect_one("?"));
   |                                                                                    ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error: aborting due to 15 previous errors

Some errors occurred: E0432, E0599, E0603.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `mutagen-plugin`.

To learn more, run the command again with --verbose.
⋊> ~/m/e/example_project on master ◦ rustc --version
rustc 1.31.0-nightly (4efdc04a5 2018-10-06)
⋊> ~/m/e/example_project on master ◦ cd ../../plugin/
⋊> ~/m/plugin on master ◦ cargo +nightly build
    Updating crates.io index
   Compiling version_check v0.1.5
   Compiling mutagen v0.1.1 (/home/pzmarzly/mutagen)
   Compiling mutagen-plugin v0.1.1 (/home/pzmarzly/mutagen/plugin)
   Compiling bitflags v1.0.4
   Compiling lazy_static v1.1.0
warning: the feature `assoc_unix_epoch` has been stable since 1.28.0 and no longer requires an attribute to enable
 --> /home/pzmarzly/mutagen/src/lib.rs:1:54
  |
1 | #![feature(specialization, atomic_min_max, try_from, assoc_unix_epoch)]
  |                                                      ^^^^^^^^^^^^^^^^
  |
  = note: #[warn(stable_features)] on by default

error[E0432]: unresolved import `syntax::codemap`
  --> src/lib.rs:18:13
   |
18 | use syntax::codemap::{Span, Spanned};
   |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
  --> src/lib.rs:23:19
   |
23 | use syntax::util::small_vector::SmallVector;
   |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`

error[E0432]: unresolved import `syntax::codemap`
 --> src/bounded_loop.rs:3:13
  |
3 | use syntax::codemap::Span;
  |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0432]: unresolved import `syntax::util::small_vector`
 --> src/bounded_loop.rs:9:19
  |
9 | use syntax::util::small_vector::SmallVector;
  |                   ^^^^^^^^^^^^ Could not find `small_vector` in `util`

error[E0432]: unresolved import `syntax::codemap`
 --> /home/pzmarzly/mutagen/plugin/target/debug/build/mutagen-plugin-0b81ecef5f38ded8/out/plugin_ops.rs:3:13
  |
3 | use syntax::codemap::Span;
  |             ^^^^^^^ Could not find `codemap` in `syntax`

error[E0603]: struct `ThinVec` is private
 --> /home/pzmarzly/mutagen/plugin/target/debug/build/mutagen-plugin-0b81ecef5f38ded8/out/plugin_ops.rs:2:72
  |
2 | use syntax::ast::{Attribute, BinOp, BinOpKind, Expr, ExprKind, NodeId, ThinVec};
  |                                                                        ^^^^^^^

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ptr::P<syntax::ast::Item>; 1]>` in the current scope
  --> src/lib.rs:93:46
   |
93 |             Annotatable::Item(p.fold_item(i).expect_one("expected exactly one item"))
   |                                              ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use syntax::fold::ExpectOne;
   |

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::TraitItem; 1]>` in the current scope
  --> src/lib.rs:96:34
   |
96 |             p.fold_trait_item(i).expect_one("expected exactly one item")
   |                                  ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use syntax::fold::ExpectOne;
   |

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::ImplItem; 1]>` in the current scope
  --> src/lib.rs:99:33
   |
99 |             p.fold_impl_item(i).expect_one("expected exactly one item")
   |                                 ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
9  | use syntax::fold::ExpectOne;
   |

error[E0599]: no method named `codemap` found for type `&'a mut syntax::ext::base::ExtCtxt<'cx>` in the current scope
   --> src/lib.rs:147:33
    |
147 |         let span_desc = self.cx.codemap().span_to_string(span);
    |                                 ^^^^^^^

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::Stmt; 1]>` in the current scope
   --> src/lib.rs:988:84
    |
988 |                 let _ = mem::replace(&mut newstmts[0], resizer.fold_stmt(coverage).expect_one("?"));
    |                                                                                    ^^^^^^^^^^
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
    |
9   | use syntax::fold::ExpectOne;
    |

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ptr::P<syntax::ast::Item>; 1]>` in the current scope
  --> src/bounded_loop.rs:26:51
   |
26 |             Annotatable::Item(plugin.fold_item(i).expect_one("expected exactly one item"))
   |                                                   ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::TraitItem; 1]>` in the current scope
  --> src/bounded_loop.rs:29:39
   |
29 |             plugin.fold_trait_item(i).expect_one("expected exactly one item")
   |                                       ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::ImplItem; 1]>` in the current scope
  --> src/bounded_loop.rs:32:38
   |
32 |             plugin.fold_impl_item(i).expect_one("expected exactly one item")
   |                                      ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error[E0599]: no method named `expect_one` found for type `smallvec::SmallVec<[syntax::ast::Stmt; 1]>` in the current scope
  --> src/bounded_loop.rs:80:84
   |
80 |                 let _ = mem::replace(&mut newstmts[0], resizer.fold_stmt(counters).expect_one("?"));
   |                                                                                    ^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           `use syntax::fold::ExpectOne;`

error: aborting due to 15 previous errors

Some errors occurred: E0432, E0599, E0603.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `mutagen-plugin`.

To learn more, run the command again with --verbose.
```

**Comment by llogiq** [comment]
I just published 0.1.2 of both the plugin and the library. This should now work again. Thanks to @gnieto who did the heavy lifting.

**Comment by zmitchell** [comment]
I'm actually still getting an error on 0.1.2. For reference I'm on macOS 10.14. When just doing `cargo mutagen --verbose` this is what I get:

```text
polarization!$ cargo mutagen --verbose               12.97s [master●] ~/Projects/polarization
       Fresh version_check v0.1.4
       Fresh rand_core v0.2.1
       Fresh libc v0.2.43
       Fresh libm v0.1.2
       Fresh rawpointer v0.1.0
       Fresh remove_dir_all v0.5.1
       Fresh fnv v1.0.6
       Fresh quick-error v1.2.2
       Fresh ucd-util v0.1.1
       Fresh bit-vec v0.5.0
       Fresh byteorder v1.2.4
       Fresh bitflags v1.0.4
       Fresh assert_approx_eq v1.0.0
       Fresh rand v0.5.5
       Fresh wait-timeout v0.1.5
       Fresh regex-syntax v0.6.2
       Fresh bit-set v0.5.0
       Fresh num-traits v0.2.5
       Fresh typenum v1.10.0
       Fresh matrixmultiply v0.1.14
       Fresh tempfile v3.0.3
       Fresh num-integer v0.1.39
       Fresh approx v0.3.0
       Fresh num-complex v0.2.0
       Fresh lazy_static v1.1.0
       Fresh generic-array v0.11.1
       Fresh rusty-fork v0.2.0
       Fresh num-bigint v0.2.0
       Fresh num-iter v0.1.37
       Fresh alga v0.7.1
       Fresh mutagen v0.1.2
       Fresh proptest v0.8.5
       Fresh num-rational v0.2.1
       Fresh nalgebra v0.16.0
   Compiling mutagen-plugin v0.1.2
       Fresh num v0.2.0
     Running `rustc --crate-name mutagen_plugin /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/lib.rs --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=e7b7d2012dc8d897 -C extra-filename=-e7b7d2012dc8d897 --out-dir /Users/zmitchell/Projects/polarization/target/debug/deps -L dependency=/Users/zmitchell/Projects/polarization/target/debug/deps --extern bitflags=/Users/zmitchell/Projects/polarization/target/debug/deps/libbitflags-fffd5f1ed5c9f142.rlib --extern mutagen=/Users/zmitchell/Projects/polarization/target/debug/deps/libmutagen-113ab7782cbc100c.rlib --cap-lints allow`
error: Could not compile `mutagen-plugin`.

Caused by:
  process didn't exit successfully: `rustc --crate-name mutagen_plugin /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/lib.rs --error-format json --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C debuginfo=2 -C metadata=e7b7d2012dc8d897 -C extra-filename=-e7b7d2012dc8d897 --out-dir /Users/zmitchell/Projects/polarization/target/debug/deps -L dependency=/Users/zmitchell/Projects/polarization/target/debug/deps --extern bitflags=/Users/zmitchell/Projects/polarization/target/debug/deps/libbitflags-fffd5f1ed5c9f142.rlib --extern mutagen=/Users/zmitchell/Projects/polarization/target/debug/deps/libmutagen-113ab7782cbc100c.rlib --cap-lints allow` (exit code: 1)
cargo test returned non-zero status
```
The last line says `cargo test returned non-zero status`, so I just ran `cargo test` and got this mountain of error messages:
```
polarization!$ cargo test                             3.06s [master●] ~/Projects/polarization
   Compiling mutagen-plugin v0.1.2
error[E0432]: unresolved import `syntax::source_map`
  --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/lib.rs:21:13
   |
21 | use syntax::source_map::{Span, Spanned};
   |             ^^^^^^^^^^ Could not find `source_map` in `syntax`

error[E0432]: unresolved import `syntax::fold::ExpectOne`
  --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/lib.rs:23:34
   |
23 | use syntax::fold::{self, Folder, ExpectOne};
   |                                  ^^^^^^^^^ no `ExpectOne` in `fold`

error[E0432]: unresolved import `syntax::source_map`
 --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/bounded_loop.rs:3:13
  |
3 | use syntax::source_map::Span;
  |             ^^^^^^^^^^ Could not find `source_map` in `syntax`

error[E0432]: unresolved import `syntax::fold::ExpectOne`
 --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/bounded_loop.rs:5:34
  |
5 | use syntax::fold::{self, Folder, ExpectOne};
  |                                  ^^^^^^^^^ no `ExpectOne` in `fold`

error[E0432]: unresolved import `syntax::source_map`
 --> /Users/zmitchell/Projects/polarization/target/debug/build/mutagen-plugin-133c0ec6732b17dd/out/plugin_ops.rs:3:13
  |
3 | use syntax::source_map::Span;
  |             ^^^^^^^^^^ Could not find `source_map` in `syntax`

error[E0053]: method `fold_impl_item` has an incompatible type for trait
   --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/bounded_loop.rs:133:5
    |
133 |     fn fold_impl_item(&mut self, i: ImplItem) -> SmallVec<[ImplItem; 1]> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rustc_data_structures::small_vec::SmallVec`, found struct `smallvec::SmallVec`
    |
    = note: expected type `fn(&mut bounded_loop::Plugin<'a, 'cx>, syntax::ast::ImplItem) -> rustc_data_structures::small_vec::SmallVec<[syntax::ast::ImplItem; 1]>`
               found type `fn(&mut bounded_loop::Plugin<'a, 'cx>, syntax::ast::ImplItem) -> smallvec::SmallVec<[syntax::ast::ImplItem; 1]>`

error[E0053]: method `fold_trait_item` has an incompatible type for trait
   --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/bounded_loop.rs:164:5
    |
164 |     fn fold_trait_item(&mut self, i: TraitItem) -> SmallVec<[TraitItem; 1]> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rustc_data_structures::small_vec::SmallVec`, found struct `smallvec::SmallVec`
    |
    = note: expected type `fn(&mut bounded_loop::Plugin<'a, 'cx>, syntax::ast::TraitItem) -> rustc_data_structures::small_vec::SmallVec<[syntax::ast::TraitItem; 1]>`
               found type `fn(&mut bounded_loop::Plugin<'a, 'cx>, syntax::ast::TraitItem) -> smallvec::SmallVec<[syntax::ast::TraitItem; 1]>`

error[E0053]: method `fold_impl_item` has an incompatible type for trait
   --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/lib.rs:470:5
    |
470 |     fn fold_impl_item(&mut self, i: ImplItem) -> SmallVec<[ImplItem; 1]> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rustc_data_structures::small_vec::SmallVec`, found struct `smallvec::SmallVec`
    |
    = note: expected type `fn(&mut MutatorPlugin<'a, 'cx>, syntax::ast::ImplItem) -> rustc_data_structures::small_vec::SmallVec<[syntax::ast::ImplItem; 1]>`
               found type `fn(&mut MutatorPlugin<'a, 'cx>, syntax::ast::ImplItem) -> smallvec::SmallVec<[syntax::ast::ImplItem; 1]>`

error[E0053]: method `fold_trait_item` has an incompatible type for trait
   --> /Users/zmitchell/.cargo/registry/src/github.com-1ecc6299db9ec823/mutagen-plugin-0.1.2/src/lib.rs:503:5
    |
503 |     fn fold_trait_item(&mut self, i: TraitItem) -> SmallVec<[TraitItem; 1]> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `rustc_data_structures::small_vec::SmallVec`, found struct `smallvec::SmallVec`
    |
    = note: expected type `fn(&mut MutatorPlugin<'a, 'cx>, syntax::ast::TraitItem) -> rustc_data_structures::small_vec::SmallVec<[syntax::ast::TraitItem; 1]>`
               found type `fn(&mut MutatorPlugin<'a, 'cx>, syntax::ast::TraitItem) -> smallvec::SmallVec<[syntax::ast::TraitItem; 1]>`

error: aborting due to 9 previous errors

Some errors occurred: E0053, E0432.
For more information about an error, try `rustc --explain E0053`.
error: Could not compile `mutagen-plugin`.

To learn more, run the command again with --verbose.
```
I haven't really dug in to see if it's the same error as above, but as soon as I saw the import error related to `syntax` I figured it was related.

**Comment by gnieto** [comment]
I've just tried the example project and I don't see that error. I think that maybe you are not using latest rust nightly compiler.

Could you try to update it and check if that helps?

**Comment by zmitchell** [comment]
Sorry, completely missed that this was for one of the included examples. I was using the nightly compiler, but updating solved this particular issue. I guess just ignore me...
